image: node:8.11.3

stages:
  - client

variables:
  DEPLOY_PATH: root@yourmachine:/path/to/app

cache:
  paths:
    - client/node_modules/

client:
  stage: client
  before_script:
    - echo "started CI/CD for client"
  script:
    - cd client
    - npm install
    - echo "running tests"
    - npm run build
  after_script:
    - echo "finished CI/CD for client"
  artifacts:
    paths:
      - build
