image: node:8.11.3

stages:
  - build

cache:
  paths:
    - client/node_modules/

build_client:
  stage: build
  before_script:
    - echo "started CI/CD for client"
    - apt-get update -qq && apt-get install -y -qq sshpass
  script:
    - cd client
    - npm install
    - echo "running tests"
    - npm run build
    - sshpass -V
    - export SSHPASS=$DEPOLY_PASS
    - echo $DEPLOY_PATH
    - sshpass -e scp -o stricthostkeychecking=no -r ./build $DEPLOY_NAME@$DEPLOY_HOST:$DEPLOY_PATH
  after_script:
    - echo "finished CI/CD for client"
  artifacts:
    paths:
      - client/build
