image: node:8.11.3

variables:
  DEPLOY_PATH: root@yourmachine:/path/to/app

cache:
  paths:
    - client/node_modules/

install_client:
  before_script:
    - echo "started install client"
  script:
    - cd client && npm install
  after_script:
    - echo "finished install client"

build_client:
  before_script:
    - echo "started build client"
  script:
    - cd client && npm run build
  after_script:
    - echo "finished build client"

test_client:
  before_script:
    - echo "started test client"
  script:
    - echo "running tests"
  after_script:
    - echo "finished test client"

deploy_client:
  before_script:
    - echo "started deploy client"
  script:
    - echo "deploy_all"
  after_script:
    - echo "finished deploy client"
